CLEANED DATA
    - Imported data
    - Binned 3 variables: BMI, MentHlth, PhysHealth
    - Standardized data type of each variable to categorical (integer values)
    - Adding merged data (HD+Stroke) as new variable at end of df

In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("/Users/calvinatkins/Downloads/Data Sets/heart_disease_health_indicators_Brfss2015.csv")
df.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [10]:
# BIN BMI
bin_edges = [0, 18.5, 24.9, 29.9, 1000]
labels = ['0', '1', '2', '3']
bins = pd.cut(df['BMI'], bins=bin_edges, labels=labels)
df.loc[:, 'BMI'] = pd.cut(df['BMI'], bins=bin_edges, labels=labels)

In [11]:
# BIN Ment Health
bin_edges_ment = [-1,9,19,100]
labels_ment = ['1', '2', '3']
bins_ment = pd.cut(df['MentHlth'], bins=bin_edges_ment, labels=labels_ment)
df.loc[:, 'MentHlth'] = pd.cut(df['MentHlth'], bins=bin_edges_ment, labels=labels_ment)

In [12]:
# BIN Physical Health
bin_edges_phys = [-1,9,19,100]
labels_phys = ['1', '2', '3']
bins_phys = pd.cut(df['PhysHlth'], bins=bin_edges_phys, labels=labels_phys)
df.loc[:, 'PhysHlth'] = pd.cut(df['PhysHlth'], bins=bin_edges_phys, labels=labels_phys)

In [17]:
df = df.astype(int)
df = df.astype('category')
print(df.dtypes)

HeartDiseaseorAttack    category
HighBP                  category
HighChol                category
CholCheck               category
BMI                     category
Smoker                  category
Stroke                  category
Diabetes                category
PhysActivity            category
Fruits                  category
Veggies                 category
HvyAlcoholConsump       category
AnyHealthcare           category
NoDocbcCost             category
GenHlth                 category
MentHlth                category
PhysHlth                category
DiffWalk                category
Sex                     category
Age                     category
Education               category
Income                  category
dtype: object

In [22]:
combo_dict = {(0, 0): 1, (0, 1): 2, (1, 0): 3, (1, 1): 4}

#Apply the mapping to the two columns and create a new column 
df["HD+Stroke"] = df.apply(lambda x: combo_dict[(x["HeartDiseaseorAttack"], x["Stroke"])], axis=1)
df.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HD+Stroke
0,0,1,1,1,3,1,0,0,0,0,...,0,5,2,2,1,0,9,4,3,1
1,0,0,0,0,2,1,0,0,1,0,...,1,3,1,1,0,0,7,6,1,1
2,0,1,1,1,2,0,0,0,0,1,...,1,5,3,3,1,0,9,4,8,1
3,0,1,0,1,2,0,0,0,1,1,...,0,2,1,1,0,0,11,3,6,1
4,0,1,1,1,1,0,0,0,1,1,...,0,2,1,1,0,0,11,5,4,1

In [23]:
df.to_csv('HD_indicators_cleaned.csv')